### PR TITLE
Tb68 Update work

### PR DESCRIPTION
**Pull request by dugite-code**
Currently working but preferences still need an update

**Todo:**
- [x] Update options.xul - https://developer.thunderbird.net/add-ons/updates/tb68#removed-xul-elements
- [x] Create preferences.js 
- [ ] Fix tooltips
- [ ] Fix Minimize/Maximize options
- [ ] Send button is getting blocked
- [x] ~~Manifest localization~~ Done in Separate Pull request

### CODE REVIEW

**Comment by michelRenon** [comment]
Thanks a lot for your contribution !
I also started to work on TB68 compatibility : I already wrote the equivalent to your 2 first commits and I'll push them this weekend. Sorry for the duplicate. Then I'll use your commit about preferences.
To avoid future duplicates, maybe we can define on which part/point we are working. Don't hesitate to inform me.

**Comment by dugite-code** [comment]
No worries, just glad I could contribute something useful. When I do any more work on it I'll make sure to keep the commits small and specific so you can cherry pick anything that you need.

**Comment by michelRenon** [comment]
I finally pushed my own branch "dev_tb68" with your last commit "Replace stringbundleset and listbox".
Sorry for being o long to push it.

Now we can work on the same branch.

**Comment by michelRenon** [comment]
Reopening this pr just to follow the progress on branch 'dev_tb68'.
I worked on finishing preferences (new list of AddressBooks) and tooltips.
From your TODO list, I'll look at the next point "minimize/maximize options"

Can you explain what is the problem with Send button ? It seems to me it is ok.
Cheers,

**Comment by dugite-code** [comment]
```

**Comment by dugite-code** [comment]
Window 10
68.1.1 with a fresh profile

```
Error: currentAccountKey '' has no matching account! MsgComposeCommands.js:3658:13
    GenericSendMessage chrome://messenger/content/messengercompose/MsgComposeCommands.js:3658
    SendMessage chrome://messenger/content/messengercompose/MsgComposeCommands.js:3960
    doCommand chrome://messenger/content/messengercompose/MsgComposeCommands.js:816
    doCommand chrome://messenger/content/messengercompose/MsgComposeCommands.js:1000
    goDoCommand chrome://global/content/globalOverlay.js:101
    oncommand chrome://messenger/content/messengercompose/messengercompose.xul:1

An error occurred executing the cmd_sendButton command: [Exception... "[JavaScript Error: "currentAccountKey '' has no matching account!" {file: "chrome://messenger/content/messengercompose/MsgComposeCommands.js" line: 3658}]'[JavaScript Error: "currentAccountKey '' has no matching account!" {file: "chrome://messenger/content/messengercompose/MsgComposeCommands.js" line: 3658}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://global/content/globalOverlay.js :: goDoCommand :: line 101"  data: yes] globalOverlay.js:104
    goDoCommand chrome://global/content/globalOverlay.js:104
    oncommand chrome://messenger/content/messengercompose/messengercompose.xul:1
```

I've not been able to trace this one down myself, I had been looking in the LoadIdentity function but nothing jumped out at me.

**Comment by michelRenon** [comment]
I got also the error on linux. And I corrected it by manually 'rebasing' LoadIdentity() from TB's source code.
Can you confirm it is ok also for you on windows ?

**Comment by dugite-code** [comment]
Excellent, that did it and works like a charm

**Comment by michelRenon** [comment]
I'm working on last todo item : "Fix Minimize/Maximize options"
We need to replace <textbox> by <html:textarea> because multiline <textbox> are not supported anymore, only one line. But it's not so easy : we have to handle ourselves the automatic resizing of textarea. I'm searching best way to do it in js.

**Pull request closed without merging**
